### PR TITLE
Fixes

### LINKED ISSUE #35: Method with trailing semi colon
This code will parse without error:
```
class Test
{
  char *name() { return ""; }
};
```

However this code generates a parse error:
```
class Test
{
  char *name() { return ""; };
};
```

### LINKED ISSUE #47: Struct with __attribute__
Structures with attributes are parsed incorrectly. For example:
```
struct __attribute__((packed)) struct1_t {
    static constexpr int A = 1;
    static constexpr int B = 2;
};
```
It seems to me, that they are taken for `function_definition` somehow.
This will help to resolve [this issue](https://github.com/EvgeniyPeshkov/syntax-highlighter/issues/21).
Thank you very much.

### LINKED ISSUE #63: Bad AST for the following code
```c
# define SHA256_CBLOCK   (SHA_LBLOCK*4)/* SHA-256 treats input data as a
                                        * contiguous array of 32 bit wide
                                        * big-endian values. */

typedef struct SHA256state_st {
    SHA_LONG h[8];
    SHA_LONG Nl, Nh;
    SHA_LONG data[SHA_LBLOCK];
    unsigned int num, md_len;
} SHA256_CTX;
```

Results in bad AST with errors. Comment style confuses tree-sitter.

```
(translation_unit 1 1 359
 (preproc_def 1 1 73
  (identifier 1 10 13)
  (preproc_arg 1 23 50)
 )
 (expression_statement 2 41 12
  (pointer_expression 2 41 12
   (identifier 2 43 10)
  )
 )
 (declaration 2 54 15
  (type_identifier 2 54 5)
  (ERROR 2 60 5
   (identifier 2 60 2)
   (number_literal 2 63 2)
  )
  (identifier 2 66 3)
 )
 (expression_statement 2 70 77
  (binary_expression 2 70 77
   (binary_expression 2 70 50
    (identifier 2 70 4)
    (identifier 3 43 3)
   )
   (ERROR 3 47 14
    (identifier 3 47 6)
    (identifier 3 54 6)
   )
   (binary_expression 3 62 11
    (pointer_expression 3 62 1
     (identifier 3 63 0)
    )
    (identifier 5 1 7)
   )
  )
 )
 (declaration 5 9 138
  (struct_specifier 5 9 126
   (type_identifier 5 16 14)
   (field_declaration_list 5 31 104
    (field_declaration 6 5 14
     (type_identifier 6 5 8)
     (array_declarator 6 14 4
      (field_identifier 6 14 1)
      (number_literal 6 16 1)
     )
    )
    (field_declaration 7 5 16
     (type_identifier 7 5 8)
     (field_identifier 7 14 2)
     (field_identifier 7 18 2)
    )
    (field_declaration 8 5 26
     (type_identifier 8 5 8)
     (array_declarator 8 14 16
      (field_identifier 8 14 4)
      (identifier 8 19 10)
     )
    )
    (field_declaration 9 5 25
     (sized_type_specifier 9 5 12
      (primitive_type 9 14 3)
     )
     (field_identifier 9 18 3)
     (field_identifier 9 23 6)
    )
   )
  )
  (identifier 10 3 10)
 )
)
```

### LINKED ISSUE #96: support list-initialization in an assignment expression
Example:

```cpp
 void test(int a) {
// tree-sitter output is
//   expression_statement [1, 3] - [1, 10])
//        compound_literal_expression [1, 3] - [1, 9])
//          type: type_identifier [1, 3] - [1, 4])
//          ERROR [1, 5] - [1, 6])
//          value: initializer_list [1, 7] - [1, 9])  
   a = {};
}
```

Looks like this is not handled in the grammar.

### LINKED ISSUE #102: Pointer-to-member-function is not parsed correctly.
testcase:

```
void (Class::*member_function_ptr)(int);
```

tree-sitter output:

```
  declaration [0, 0] - [0, 40])
    type: primitive_type [0, 0] - [0, 4])
    declarator: function_declarator [0, 5] - [0, 39])
      declarator: parenthesized_declarator [0, 5] - [0, 34])
        scoped_identifier [0, 6] - [0, 33])
          namespace: namespace_identifier [0, 6] - [0, 11])
          ERROR [0, 13] - [0, 14])
          name: identifier [0, 14] - [0, 33])
      parameters: parameter_list [0, 34] - [0, 39])
        parameter_declaration [0, 35] - [0, 38])
          type: primitive_type [0, 35] - [0, 38])
```

Looks like the `*` is not well recognized.

### LINKED ISSUE #103: direct-list-initialization with primitive type "int{1}" is not parsed correctly.
```
int {1}; // tree-sitter cannot parsed it.
Foo {1}; // ok: it is parsed as compound_literal_expression 
```

tree-sitter output for `int {1};`

```
 ERROR [0, 0] - [0, 3])
    primitive_type [0, 0] - [0, 3])
  compound_statement [0, 3] - [0, 6])
    ERROR [0, 4] - [0, 5])
      number_literal [0, 4] - [0, 5])
```

### LINKED ISSUE #112: `alignas` is not supported
https://en.cppreference.com/w/cpp/language/alignas

Example:
```
class alignas(uintptr_t) JitScript final : public TrailingArray {
}
```

### LINKED ISSUE #139: noexcept can't be followed by __attribute__
failed to parse the following code:

```cpp
inline constexpr vk::SparseMemoryBindFlags operator|(vk::SparseMemoryBindFlagBits bit0, vk::SparseMemoryBindFlagBits bit1) noexcept __attribute__((always_inline)) {
}
```

the current parser doesn't allow noexcept followed by __attribute__

```
translation_unit [0, 0] - [2, 0]
  function_definition [0, 0] - [1, 1]
    storage_class_specifier [0, 0] - [0, 6]
    type_qualifier [0, 7] - [0, 16]
    type: qualified_identifier [0, 17] - [0, 42]
      scope: namespace_identifier [0, 17] - [0, 19]
      name: type_identifier [0, 21] - [0, 42]
    declarator: function_declarator [0, 43] - [0, 162]
      declarator: operator_name [0, 43] - [0, 52]
      parameters: parameter_list [0, 52] - [0, 122]
        parameter_declaration [0, 53] - [0, 86]
          type: qualified_identifier [0, 53] - [0, 81]
            scope: namespace_identifier [0, 53] - [0, 55]
            name: type_identifier [0, 57] - [0, 81]
          declarator: identifier [0, 82] - [0, 86]
        parameter_declaration [0, 88] - [0, 121]
          type: qualified_identifier [0, 88] - [0, 116]
            scope: namespace_identifier [0, 88] - [0, 90]
            name: type_identifier [0, 92] - [0, 116]
          declarator: identifier [0, 117] - [0, 121]
      ERROR [0, 123] - [0, 131]
      attribute_specifier [0, 132] - [0, 162]
        argument_list [0, 146] - [0, 161]
          identifier [0, 147] - [0, 160]
    body: compound_statement [0, 163] - [1, 1]
```

### LINKED ISSUE #178: Group members under the same Access Specifier
**Context**
This piece of C++ code:
```
class Test {
    int a;
public:
    float b;
};
```
parses to this syntax tree:
```
(translation_unit [0, 0] - [5, 0]
  (class_specifier [0, 0] - [4, 1]
    name: (type_identifier [0, 6] - [0, 10])
    body: (field_declaration_list [0, 11] - [4, 1]
      (field_declaration [1, 1] - [1, 7]
        type: (primitive_type [1, 1] - [1, 4])
        declarator: (field_identifier [1, 5] - [1, 6]))
      (access_specifier [2, 0] - [2, 7])
      (field_declaration [3, 4] - [3, 12]
        type: (primitive_type [3, 4] - [3, 9])
        declarator: (field_identifier [3, 10] - [3, 11])))))
```

I'm wondering about how hard it is to **group members by access specifier**; which would produce something like this:
```
(translation_unit [0, 0] - [5, 0]
  (class_specifier [0, 0] - [4, 1]
    name: (type_identifier [0, 6] - [0, 10])
    body: (field_declaration_list [0, 11] - [4, 1]
      (field_declaration [1, 1] - [1, 7]
        type: (primitive_type [1, 1] - [1, 4])
        declarator: (field_identifier [1, 5] - [1, 6]))
      (access_specifier [2, 0] - [3, 11]
      (field_declaration [3, 4] - [3, 12]
        type: (primitive_type [3, 4] - [3, 9])
        declarator: (field_identifier [3, 10] - [3, 11]))))))
```
> Note that the second `field_declaration` is inside the `access_specifier` thing.

I see two aspects for this:
1. Backward compatibility; where we still need the "implicitly-defined-access-specifier" members.
2. I assume this is not hard to implement (boils down to modifying the `access_modifier` grammar rule only)

**Benefits**
I'm trying to write a tool to generate customizable class/object diagrams from C++ headers; using `tree-sitter-graph`. And having
the access information of members bundled into the syntax tree will enormously simplify things.

### LINKED ISSUE #203: Inconsistent highlighting of `alignas` in C++
All `alignas` except the first one will be highlighted as functions.
Screen Shot 2023-05-12 at 9 41 25 AM
With semantic highlighting enabled, it shows as below.
Screen Shot 2023-05-12 at 9 43 47 AM
I've also submitted an issue to nvim-treesitter [#4787](https://github.com/nvim-treesitter/nvim-treesitter/issues/4787). There were some more details.

### PR DESCRIPTION
**Pull request by amaanq**
Did this to prep for another release, and most of these were easy enough to fix and aren't anything complicated.

The main change that really increased state count a bit is backporting the C updates where I added attribute_specifier to more allowed locations. 

Closes #47 
Closes #63 (really a C bug fixed in 0.20.4)
Closes #96 
Closes #102 
Closes #103 
Closes #112 
Closes #139 
Closes #203 

The last issue that's a bit difficult is the parenthesized assignment expressions, that's because of fold operators taking precedence over them but I could not figure that out, I'll try a bit more anyways

### CODE REVIEW

File: grammar.js [hunk 1]
```diff
@@ -1178,18 +1178,27 @@ module.exports = grammar(C, {
...
-        field('operator', choice(
-          'and_eq',
-          'or_eq',
-          'xor_eq',
-        )),
-        field('right', $._expression),
+    assignment_expression: $ => prec.right(PREC.ASSIGNMENT, seq(
+      field('left', $._assignment_left_expression),
+      field('operator', choice(
+        '=',
```
Comment (DennySun2100) [inline grammar.js:1223]: Why do we need to move the c operators here instead of inheriting

Comment (amaanq) [reply grammar.js:1223]: rhs includes initializer list

**Comment by jdrouhard** [comment]
I'll take a look at this at some point tomorrow. Thanks for working on this!

File: grammar.js (hunk 1 above)
Comment (DennySun2100) [reply grammar.js:1223]: I see, this is only supported in c++, so we have to copy the list of c operators to the assignment_expression of c++ grammar?

Comment (amaanq) [reply grammar.js:1223]: yep

Comment (DennySun2100) [reply grammar.js:1223]: Btw, Amaan, I hit another problem related to assignment_expression, right now c++ parser is not able to parse a parenthesized assignment_expression with the c operators, for example, if(arg += 1) cannot be parsed by c++ parser, but if(arg and_eq 1) can. Have you ever hit the same problem?

Comment (amaanq) [reply grammar.js:1223]: yeah the last tidbit in my pr message is just about that, it's a complicated one that I'm not sure I can solve but I'll try some more ideas tonight

Comment (DennySun2100) [reply grammar.js:1223]: This is great to know, my project is confronted with this issue, I am glad to help if you need some hands, or someone to review, I am looking forward to your fix, good luck!

File: grammar.js [hunk 2]
```diff
@@ -416,7 +423,34 @@ module.exports = grammar(C, {
...
+      ';',
+    ),
+
+    access_specifier_list: $ => prec.right(seq(
+      $.access_specifier,
+      ':',
+      repeat($._access_specifier_list_item),
+    )),
+
+    _access_specifier_list_item: $ => choice(
```
Comment (jdrouhard) [inline grammar.js:440]: I know this is resolving a particular issue, but so far I've specifically avoided doing this.

Convince me otherwise, but I don't think the visibility labels (public, private, etc), should have other field declarations as children. It introduces another potential parent for the declarations instead of them always being children of the class declaration.

I also think in cases like this, reusing the same rules (letting them support recursion or whatever) is normally a lot better from maintenance burden perspective--I'm not too excited about the duplication of nearly all field declaration rules here save the access specifier just to achieve this. 

Overall I think your PR looks good, but can we back this particular change out for now and discuss in an issue or a PR on its own?

File: grammar.js [hunk 3]
```diff
@@ -66,6 +62,7 @@ module.exports = grammar(C, {
     [$._binary_fold_operator, $._fold_operator],
     [$.expression_statement, $.for_statement],
     [$.init_statement, $.for_statement],
+    [$._function_declarator_seq],
```
Comment (jdrouhard) [inline grammar.js:65]: What was the new conflict here?

File: grammar.js [hunk 4]
```diff
@@ -416,7 +423,34 @@ module.exports = grammar(C, {
       alias($.operator_cast_definition, $.function_definition),
       alias($.operator_cast_declaration, $.declaration),
       $.friend_declaration,
-      seq($.access_specifier, ':'),
+      $.access_specifier_list,
+      $.alias_declaration,
+      $.using_declaration,
+      $.type_definition,
+      $.static_assert_declaration,
+      ';',
```
Comment (jdrouhard) [inline grammar.js:431]: Semicolons can technically appear anywhere a statement is valid. I think you were trying to close a particular issue regarding having an extraneous semicolon (#35?), but I think we should hold off and try to figure out a way to make "empty" statements (a single semicolon) work anywhere a statement could appear (any of which would end with a semicolon), instead of only as a field declaration.

Not sure how terrible that would be for node count though :)

**Review by jdrouhard — CHANGES_REQUESTED** [review]

File: grammar.js (hunk 2 above)
Comment (amaanq) [reply grammar.js:440]: >  It introduces another potential parent for the declarations instead of them always being children of the class declaration.

I can understand the downsides of this - I'll remove it for tihs PR.

File: grammar.js (hunk 3 above)
Comment (amaanq) [reply grammar.js:65]: ` repeat($.attribute_specifier)` after noexcepts

File: grammar.js (hunk 4 above)
Comment (amaanq) [reply grammar.js:431]: Hm, maybe something like javascript's automatic semicolons could be used, only adds 7 to state count though

Comment (jdrouhard) [reply grammar.js]: Not familiar with that, but I think we should make something like an `empty_statement: $ => ';'` rule and just put that as an option in various places where other statements (including top level) can be. Not the most elegant and I haven't actually tried this so it may not really work in practice but something like that is the best way to make the grammar not choke on extra semicolons.

Comment (amaanq) [reply grammar.js]: https://github.com/tree-sitter/tree-sitter-javascript/blob/master/src/scanner.c, though C++ is a bit different and an empty_statement node would be just fine as well - but I think naming it `_empty_statement`  to hide the rule could be better

**Review by jdrouhard — APPROVED** [review]
Don't forget to update the list of issues this will close since we're punting a couple for another PR.

Looks good

**Comment by DennySun2100** [comment]
Hi @amaanq, 

I am asking this just in case I miss it, are you working on the fix for the precedence issue of parenthesized assignment expressions?

**Comment by amaanq** [comment]
Thanks for the reminder, I've come up with a solution now but I'd appreciate more testing for potential pitfalls.

**Comment by DennySun2100** [comment]
> Thanks for the reminder, it slipped my mind completely. I've come up with a solution now but I'd appreciate more testing for potential pitfalls. #219

It's great to hear you've got a solution, looking forward to seeing the PR soon.
